version: '3'

tasks:
    build:quarkus:jar:
        dir: java-function
        cmds:
            - ./gradlew build
    build:quarkus:native:
        dir: java-function
        cmds:
            - ./gradlew build -Dquarkus.native.enabled=true -Dquarkus.package.jar.enabled=false

