version: '3'

tasks:
    build:java-function:jar:
        dir: java-function
        cmds:
            - gradle build
    build:java-function:native:
        dir: java-function
        cmds:
            - gradle build -Dquarkus.native.enabled=true -Dquarkus.package.jar.enabled=false

