name: upload to S3
description: A reusable action to upload files to S3
inputs:
    artifact-name:
        description: Name of the artifact to upload
        required: true
    s3-bucket:
        description: S3 bucket name
        required: false
        default: mte-functions-code
    s3-path:
        description: Path in the S3 bucket to upload the artifact
        required: true
    aws-access-key-id:
        description: AWS access key
        required: true
    aws-secret-access-key:
        description: AWS secret access key
        required: true
runs:
    using: "composite"
    steps:
        -   name: download artifact
            id: download_artifact
            uses: actions/download-artifact@v4
            with:
                name: ${{ inputs.artifact-name }}
                path: ./function-code/
        -   name: configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v3
            with:
                aws-access-key-id: ${{ inputs.aws-access-key-id }}
                aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
                aws-region: eu-central-1
        -   name: upload to S3
            run: |
                aws s3 cp "${{ steps.download_artifact.outputs.download-path }}" "s3://${{ inputs.s3-bucket }}/${{ inputs.s3-path }}" --recursive
            shell: bash