name: Build functions

on:
  push:
    paths:
      - "java-function/**"
      - "kotlin-function/**"
      - "taskfile.yml"

permissions:
  id-token: write
  contents: read

jobs:
  build-java-function-jar:
    runs-on: ubuntu-latest
    container:
      image: gradle:jdk21-jammy
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install taskfile
        uses: ./.github/actions/install_taskfile
      - name: preinstall dependencies
        run: |
          task --version
      - name: build
        run: task build:java-function:jar
      - name: publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: java-function-jar
          path: java-function/build/java-function-1.0.0-runner.jar
  upload-java-function-jar:
    needs: build-java-function-jar
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: upload to S3
        uses: ./.github/actions/upload_to_s3
        with:
          artifact-name: java-function-jar
          s3-path: java-function-jar
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build-java-function-native:
    runs-on: ubuntu-latest
    container:
      image: gradle:jdk21-graal-jammy
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install taskfile
        uses: ./.github/actions/install_taskfile
      - name: preinstall dependencies
        run: |
          task --version
      - name: build
        run: task build:java-function:native
      - name: publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: java-function-native
          path: java-function/build/function.zip
  upload-java-function-native:
    needs: build-java-function-native
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: upload to S3
        uses: ./.github/actions/upload_to_s3
        with:
          artifact-name: java-function-native
          s3-path: java-function-native
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build-kotlin-function-jar:
    runs-on: ubuntu-latest
    container:
      image: gradle:jdk21-jammy
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install taskfile
        uses: ./.github/actions/install_taskfile
      - name: preinstall dependencies
        run: |
          task --version
      - name: build
        run: task build:kotlin-function:jar
      - name: publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: kotlin-function-jar
          path: kotlin-function/build/libs/kotlin-function-1.0-all.jar
  upload-kotlin-function-jar:
    needs: build-kotlin-function-jar
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: upload to S3
        uses: ./.github/actions/upload_to_s3
        with:
          artifact-name: kotlin-function-jar
          s3-path: kotlin-function-jar
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  #  install zip
  build-kotlin-function-js:
    runs-on: ubuntu-latest
    container:
      image: gradle:jdk21-jammy
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install taskfile
        uses: ./.github/actions/install_taskfile
      - name: preinstall dependencies
        run: |
          task --version
      - name: build
        run: task build:kotlin-function:js
      - name: publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: kotlin-function-js
          path: kotlin-function/build/lambda/kotlin-function-js.zip
  upload-kotlin-function-js:
    needs: build-kotlin-function-js
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: upload to S3
        uses: ./.github/actions/upload_to_s3
        with:
          artifact-name: kotlin-function-js
          s3-path: kotlin-function-js
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # TODO: build only native
  build-kotlin-function-native:
    runs-on: ubuntu-latest
    container:
      image: gradle:jdk21-graal-jammy
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install taskfile
        uses: ./.github/actions/install_taskfile
      - name: preinstall dependencies
        run: |
          task --version
          apt-get update 
          apt-get install -y curl libcurl4-openssl-dev unzip zip
        shell: bash
      - name: build
        run: task build:kotlin-function:native
      - name: publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: kotlin-function-native
          path: kotlin-function/build/lambda/release/kotlin-function.zip
  upload-kotlin-function-native:
    needs: build-kotlin-function-native
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: upload to S3
        uses: ./.github/actions/upload_to_s3
        with:
          artifact-name: kotlin-function-native
          s3-path: kotlin-function-native
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
